name             'load-generator'
maintainer       'Joel Scheuner'
maintainer_email 'joel.scheuner.dev@gmail.com'
license          'MIT'
description      'Installs/Configures load-generator'
long_description 'Installs/Configures load-generator'
version          '0.1.0'

depends 'apt', '~> 2.7.0'
depends 'git', '~> 4.2.2'
depends 'sudo', '~> 2.7.1'
depends 'rbenv', '~> 1.7.1'
depends 'openssl', '~> 4.0.0'
depends 'database', '~> 4.0.6'
depends 'postgresql', '~> 3.4.18'
depends 'nginx', '~> 2.7.6'
depends 'ark', '~> 0.9.0'

# Only for 'java_custom' recipe
# depends 'java', '~> 1.31.0'
