SSH_USERNAME = 'ubuntu'
VAGRANTFILE_API_VERSION = 2
Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.box = 'aws'
  config.vm.box_url = 'https://github.com/mitchellh/vagrant-aws/raw/master/dummy.box'

  config.vm.provider :aws do |aws, override|
    aws.access_key_id = ENV['AWS_ACCESS_KEY_ID']
    aws.secret_access_key = ENV['AWS_SECRET_ACCESS_KEY']

    aws.keypair_name = ENV['EC2_KEYPAIR']
    override.ssh.private_key_path = ENV['EC2_PRIVATE_KEY']
    override.ssh.username = SSH_USERNAME
    aws.region = 'eu-west-1'
    aws.availability_zone = 'eu-west-1a'
    # Official Ubuntu 14.04 LTS (hvm:ebs) image for eu-west-1 from Canonical:
    #  https://cloud-images.ubuntu.com/locator/ec2/
    aws.ami = 'ami-acb59bdf'
    aws.instance_type = 't2.micro'
    # # Make sure HTTP port is open!
    aws.security_groups = ['cwb-web']
    aws.tags = { 'Name' => 'cwb-load-generator' }
  end

  config.berkshelf.enabled = true
  config.berkshelf.berksfile_path = '../cookbooks/load-generator/Berksfile'
  config.omnibus.chef_version = '12.8.1'
  config.vm.provision 'chef_solo' do |chef|
    # Wrong Ruby version causes failure on first run because
    # the installed Ruby is only reflected in the path after relogin.
    # chef.attempts = 2
    chef.provisioning_path = '/etc/chef'
    chef.cookbooks_path = '../cookbooks/load-generator'
    chef.add_recipe 'load-generator'
    chef.json = {
      "postgresql": {
        "password": {
          "postgres": "thepostgresrootpassword"
        }
      },
      "load-generator": {
        "db": {
          "password": "theloadgeneratorapppassword",
        },
        "env": {
          "SECRET_KEY_BASE": "3fe397575565365108556c3e5549f139e8078a8ec8fd2675a83de96289b30550a266ac04488d7086322efbe573738e7b3ae005b2e3d9afd718aa337fa5e329cf"
        }
      }
    }
  end
end
